# Generated by Django 3.0.6 on 2020-05-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inc_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='inc_mgmt/media/tickets/'),
        ),
        migrations.AlterField(
            model_name='ticketupdate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='inc_mgmt/media/tickets/'),
        ),
    ]
