# Generated by Django 3.0.6 on 2020-06-03 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inc_mgmt', '0004_auto_20200603_1053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
