# Generated by Django 3.0.6 on 2020-06-03 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('content', models.TextField(verbose_name='content')),
                ('password', models.CharField(editable=False, max_length=255, verbose_name='password')),
                ('allowed_to_emails', models.CharField(max_length=255, null=True, verbose_name='allowed emails')),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='creation time')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
