# Generated by Django 3.0.6 on 2020-06-03 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200603_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='allowed_to_emails',
        ),
    ]
