# Generated by Django 3.0.6 on 2020-06-04 14:03

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20200603_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to=chat.models.get_upload_path),
        ),
    ]
